name: Kill Zombie Deployment

on:
  workflow_dispatch: 

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  kill-it:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel specific deployment
        run: |
          echo "Zombi i≈ülem iptal ediliyor..."
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pages/deployments/673edaf7095bef01ac6453dc79fae4a8237baeb9/cancel